### ISSUE TITLE
Update FAQ on remote execution

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel-website#122]
I think this needs an update: https://www.bazel.build/faq.html#does-bazel-require-a-build-cluster

**Comment by philwo** [comment]
@bergsieker Could you please route this to an appropriate person who could update this text in our FAQ considering that RBE exists now?

**Comment by michelleirvine** [comment]
We have a blog in the works. When we publish that, will update this FAQ as well.

Thanks for pointing this out.

**Comment by laurentlb** [comment]
Can someone update the FAQ?

cc @buchgr

**Comment by jin** [comment]
This now says "Bazel runs build operations locally by default. However, Bazel can also connect to a build cluster for even faster builds and tests. See our documentation on remote execution and remote caching for further details."
