### ISSUE TITLE
Remove the Support page from the docs, move it to website

### ISSUE THREAD

**Issue by steren** [bazelbuild/bazel-website#19]

**Comment by davidzchen** [comment]
The Support page is currently linked to from the Documentation sidebar nav. If we move it to the website, where would you recommend adding the link? Aside from the FAQ, other pages use the Contributing nav.

**Comment by steren** [comment]
We also link to the page it in the footer. And the footer contains a 'support' section.

The idea was that the content of the support page is really independent from the source code, and does not contain real documentation. So technically, I would like it to be stored outside of the main repo.

I think we can still link to it from the Documentation nav and it would open a page with no nav on bazel.builg, like for the FAQ. What do you think?

**Comment by davidzchen** [comment]
SGTM. I'll send the CLs for this change later today.

**Comment by steren** [comment]
This os not blocking IMO, we can live with the Support page in the docs, at least until we have launched the new site.
