### ISSUE TITLE
CONTRIBUTING.md name collision on case-insensitive filesystems

### ISSUE THREAD

**Issue by davidzchen** [bazelbuild/bazel-website#2]
Pasting my comment on commit aaf0f33ac9839727e4155e6cab6bc7eeb4220ac1:

One problem with this change is that we have two files named contributing.md and CONTRIBUTING.md in the root of the source tree. Unfortunately, file systems that are case-insensitive by default, such as HFS+ on macOS, get confused because of this. :/

How about if we either rename CONTRIBUTING.md back to CONTRIBUTING or rename contributing.md to contribute.md? The former might be the safer change since the latter changes the URL of a page on the site and may result in dead links.

**Comment by steren** [comment]
Ah yes, this explains why I did not name it with ".md" in the first place.
