### ISSUE TITLE
Document that P3 issue are "up-for-grab"

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/bazel-website#208]
Hi,
I was browsing the issues and stumbled on to one which I might want to take but I'm not sure if it will be welcomed for various reasons.
WDYT about marking issues as "up-for-grab" and thus signaling to community members their help would be appreciated there?

**Comment by laurentlb** [comment]
There's a pending PR (https://github.com/bazelbuild/bazel-website/pull/209).

But I don't think P4 means "up-for-grab". It just means that something is not a priority for the team. I'd recommend contributors to pick unassigned P1, P2, or P3 issues as they are considered more important.

**Comment by aiuto** [comment]
P4 issues, otoh, give a newcomer a chance to establish a working
relationship with time pressure of a P1.

**Comment by ittaiz** [comment]
My 2c- if you want to accept contributions you need to signal what is
likely to work. We all know there are many issues where only a googler is
likely to succeed.
A newcomer doesn’t know that.

**Comment by laurentlb** [comment]
My recommendation is to comment on the issues that you care about. If something is important to you and you're willing to spend time working on it, you can state it.

Having newcomers is not really a goal (we don't have the resources to do any kind of mentoring). I'd rather have fewer but regular contributors.

**Comment by aiuto** [comment]
Handing over to @sventiffe, since he is trying to fix the priority assignments.

**Comment by sventiffe** [comment]
I'm closing this issue as P4 are not considered to be up for grab. P3 issues are encouraged though as per https://bazel.build/contribute/maintainers-guide?hl=en#priority

Technically this is documented, but not very visibly. It probably should be more prominent on https://bazel.build/contribute?hl=en (I wonder how newbies actually experience the "first contact" with our contribution instructions, maybe it needs a revamp all together?).

I'll let @jdob chime in as well
