### ISSUE TITLE
Broken Link in Site Navigation - Building for Platforms

### ISSUE THREAD

**Issue by 97209** [bazelbuild/bazel-website#211]
When I click the link for Building for Platforms in the main left-hand site navigation, I get a 404 message returned from the server.

**Comment by laurentlb** [comment]
Thanks for the report. The page is visible here: https://docs.bazel.build/versions/master/platforms-intro.html

@ulfjack 
The menu is not versioned, so the current workaround is to use `{% if major_version ...`. :(

**Comment by ulfjack** [comment]
It wasn't me. I just imported the change.

**Comment by gregestren** [comment]
I was hoping to find some way to link this off the 1.0 documentation even though it was submitted after the 1.0 baseline. I can't find any reasonable way to do that though.

Ideally I'd like this published now.

In the meantime I'll restricted it to 1.1+ as described above.
