### ISSUE TITLE
Update style to match docs.bazel.build

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel-website#221]
The style of https://docs.bazel.build/versions/master/bazel-overview.html is quite different from https://www.bazel.build/contributing.html.

**Comment by gregestren** [comment]
https://github.com/bazelbuild/bazel/issues/10793 is intended to solve this by porting the CSS style to a commonly consumed location.

**Comment by jin** [comment]
Fixed by https://github.com/bazelbuild/bazel-website/pull/235
