### ISSUE TITLE
The contributing page mixes developer setup with governance

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/bazel-website#233]
This conflates two entirely distinct topics. The guidelines for engagement with the community should be distinct from the tips about how to get started.

We should split this in to at last 2 pages.

**Comment by jin** [comment]
@aiuto did you mean to create a new `documentation` label?

**Comment by aiuto** [comment]
Yes. That way it will show up in some stat gathering I am doing across all the repos.

**Comment by jin** [comment]
Oh, I hadn't realize this is the bazel-website repo, not bazel. Sorry for the noise.

**Comment by aiuto** [comment]
Now I am curious at a meta level. Do you watch an event stream that tells
you this was a new label? I don't see notifications for new labels.

**Comment by jin** [comment]
Not a stream for labels. I watch GitHub notifications for issue/PR updates,
and when I clicked on this issue, I realized the documentation tag is of a
different color :)
