### ISSUE TITLE
slack.bazel.build is down

### ISSUE THREAD

**Issue by jin** [bazelbuild/bazel-website#251]
The self-inviter we're using uses the legacy token mechanism, which Slack has turned down.

Turns out that we don't need that anymore, since Slack now supports non-expiring invite links: https://bazelbuild.slack.com/join/shared_invite/zt-dzm4qj0h-maSR3EcEr8SWE1f7dA55zw#/

If you're signed in to the workspace, clicking on this link redirects you to the workspace.

If you're not signed in to the workspace. clicking on this link provides you with a sign up form. I think we can turn down the self-inviter service and configure the service behind slack.bazel.build to redirect to https://bazelbuild.slack.com/join/shared_invite/zt-dzm4qj0h-maSR3EcEr8SWE1f7dA55zw#/.

cc @philwo @fweikert

**Comment by jin** [comment]
Could we redirect slack.bazel.build to the slack.com invite link?

**Comment by philwo** [comment]
@jin Hey, sorry that I didn't follow up earlier!

AFAIK the `slack.bazel.build` domain currently points to Google Cloud Run. I think we can deploy a container that just serves a redirect until we figure out a better solution... I'll have a look.

**Comment by jin** [comment]
Yeah, that seems like the simplest workaround for now! Thanks for taking a look.

**Comment by philwo** [comment]
The redirect is online! I'll update our documentation how I built and deployed the container tomorrow. :)

**Comment by jin** [comment]
Yay! Thanks @philwo! This is a much better experience for signed-in users, too :)

**Comment by hicksjoseph** [comment]
Just tried, got a redirect eventually to "https://bazelbuild.slack.com/join/shared_invite/zt-dzm4qj0h-maSR3EcEr8SWE1f7dA55zw#/shared-invite-legacy/error : "This link is no longer active
To join this workspace, you’ll need to ask the person who originally invited you for a new link."

**Comment by aiuto** [comment]
+Yun Peng ***@***.***>

**Comment by hicksjoseph** [comment]
I have been looking around and it looks like this is the non-expiring Slack invitation link for bazelbuild: https://join.slack.com/t/bazelbuild/shared_invite/zt-12qiikgw6-qYqQMtD3aFxLQrA_77xV5Q

Let's redirect slack.bazel.build to the link above.

Actually, it will expire after 2000 people join with this link, but won't expire within a set timeframe.

**Comment by meteorcloudy** [comment]
https://slack.bazel.build/ is now working.

**Comment by meteorcloudy** [comment]
It should be fixed now!
https://github.com/bazelbuild/continuous-integration/pull/1319

**Comment by rockwotj** [comment]
@meteorcloudy looks like it's broken again

**Comment by meteorcloudy** [comment]
Hmm, looks like the invitation link still expires after 30 days.

**Comment by Wyverald** [comment]
The link now only serves 100 people before expiring, no matter what the expiration date is.

**Comment by meteorcloudy** [comment]
Is there a way to remove that limit? Or we just have to update the link when we notice it doesn't work?

**Comment by Wyverald** [comment]
per discussion on slack (heh), we could set up https://github.com/rauchg/slackin

**Comment by meteorcloudy** [comment]
Got it!

**Comment by aiuto** [comment]
+Jason Dobies ***@***.***>

**Comment by meteorcloudy** [comment]
@jin Can you look into how to setup slackin since you have the experience?

**Comment by jin** [comment]
I just caught up with the history here -- slackin uses legacy Slack API tokens, which Slack stopped generating, and legacy APIs, which no longer work.

See https://github.com/rauchg/slackin/issues/417 and https://github.com/rauchg/slackin/issues/416

It appears that expiring links are a common complain towards Slack as well: https://github.com/integrations/slack/issues/1063

I think we need a different solution than rebooting Slackin.

**Comment by dwirandytlvk** [comment]
Is any update about this? I still looking the slack URL here

**Comment by meteorcloudy** [comment]
@dwirandytlvk We just updated the invitation link, slack.bazel.build should work now.

**Comment by snakethatlovesstaticlibs** [comment]
Hello, just wanted to let the team know that the invite is currently expired

**Comment by meteorcloudy** [comment]
Thanks for reporting, this is fixed (again...)

**Comment by snakethatlovesstaticlibs** [comment]
Thanks for taking a look! I just checked slack.bazel.build and it doesn't seem to work for me

**Comment by meteorcloudy** [comment]
@snakethatlovesstaticlibs Can you check again if it's now fixed?

**Comment by snakethatlovesstaticlibs** [comment]
I had to open https://slack.bazel.build in an incognito window but it works now, I cleared my browser history but that wasn't sufficient without incognito. Thanks for helping!
