### ISSUE TITLE
The page listing commercial remote execution vendors should be on this site rather than in the versioned docs.

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/bazel-website#262]
Complementary bug to https://github.com/bazelbuild/bazel/issues/11883

cc: @floriographygoth

**Comment by zachgrayio** [comment]
As a vendor, I actually agree here

**Comment by aiuto** [comment]
This was done on 20210407 by @communikit 

The new page is https://bazel.build/remote-execution-services.html

The versioned docs about RBE https://docs.bazel.build/versions/main/remote-execution.html, point to this new page.
