### ISSUE TITLE
The list of RBE vendors belongs on the bazel.build main site rather than in the reference docs.

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/bazel-website#284]
This page  https://docs.bazel.build/versions/3.7.0/remote-execution.html
should be split so that
- the list of vendors is moved to this site.
- the page contains a reference to the newly created list

Rationale: The group of vendors is independent of the Bazel version. New ones can start up at any time, and can service most existing Bazel versions. We serve the community best by keeping them in a place where new services are seen by users of all Bazel versions.

**Comment by zachgrayio** [comment]
I agree here, always irked me a little to see it there, but it's also unfortunate to be left off the list 🤦 

is this something the community (flare) can get done?

**Comment by aiuto** [comment]
cc: @floriographygoth @hicksjoseph

Thanks for the enthusiasm, but that one is on the Bazel team.  We need to reorganize the entire doc set for readability and utility. It needs a significant restructuring rather than local fixes.

**Comment by aiuto** [comment]
Silly me.  I forgot I opened the same bug before as #262.   Closing this one as a duplicate.
