### ISSUE TITLE
Add Bootstrap and Font Awesome CSS and JS assets

### ISSUE THREAD

**Issue by davidzchen** [bazelbuild/bazel-website#3]
The site currently does not render properly because the Bootstrap and Font Awesome CSS, JS, and font assets are missing.

In the bazelbuild/bazel repo, these assets live separately under `third_party`. @steren - do we need also need to keep these assets separate under a `third_party` directory in this repo as well or would it be fine to directly add them to the `assets/` directory?

**Comment by steren** [comment]
I would still follow Google's open source guideline and put them in `third_party` at the root of this repo

**Comment by davidzchen** [comment]
Sounds good. I will do that.

**Comment by davidzchen** [comment]
I am trying to build the `:jekyll-tree` tar in my branch (https://github.com/davidzchen/bazel-website/tree/third-party) but am running into some interesting errors raised by `pkg_tar`.
 Opened bazelbuild/bazel#2909.
