### ISSUE TITLE
social preview is not working properly

### ISSUE THREAD

**Issue by steren** [bazelbuild/bazel-website#48]
Twitter is not showing an image preview when posting https://bazel.build:
https://twitter.com/bazelbuild/status/880100968213426176

And G+ is using the Huawei logo. This logo is the only .png on the page.

Our page contains an og:image tag, so this is surprising.

Let's try to add schema.org metadata to be sure (docs at https://developers.google.com/+/web/snippet/)

**Comment by steren** [comment]
Ah, I think we need an absolute link for the og:image tag

**Comment by davidzchen** [comment]
Good call. Using an absolute URL did the trick. Thanks!

**Comment by ZeeshanAhmadKhalil** [comment]
@davidzchen  I didn't understand what do you mean by absolute URL. I want to show the social preview Image I just uploaded instead of my profile picture when I share the link of my repository.

How I can get the absolute URL of my repository?
