### ISSUE TITLE
Python FAQ entry is outdated?

### ISSUE THREAD

**Issue by cvrebert** [bazelbuild/bazel-website#57]
https://bazel.build/faq.html#what-about-python acts like there's no built-in Python support in Bazel, but there is now, per
https://docs.bazel.build/versions/master/be/python.html and https://github.com/bazelbuild/bazel/commit/4229823937ad6c6395fefd51b5f617a40d4ce46b
Furthermore, the FAQ entry refers to https://github.com/bazelbuild/bazel/blob/master/tools/build_rules/py_rules.bzl , which does not exist.

**Comment by steren** [comment]
@davidstanke maybe you can do a pass on the FAQ? It seems quite outdated overall.

IMO language support does not belong into the FAQ, but into the "build encyclopedia". FAQ should be more for things like: "why did you release Bazel?" "Can I use it at my company?"

**Comment by gregestren** [comment]
Obsolete?

**Comment by brandjon** [comment]
I believe so.
