### ISSUE TITLE
Document the "nosandbox" execution_requirement on actions

### ISSUE THREAD

**Issue by mmorearty** [bazelbuild/bazel-website#79]
In [a comment](https://github.com/bazelbuild/bazel/issues/4153#issuecomment-346678852), @ulfjack  mentioned that an action can be marked as `"nosandbox"`. This is not documented anywhere that I can find. Can you add it to the web page?

I'm pretty sure, from looking at the code, that this is a marker that can be put in the `"execution_requirements"` for [`ctx.action.run()`](https://docs.bazel.build/versions/master/skylark/lib/actions.html#run) or [`ctx.actions.run_shell()`](https://docs.bazel.build/versions/master/skylark/lib/actions.html#run_shell) (or the older, deprecated [`ctx.action()`](https://docs.bazel.build/versions/master/skylark/lib/ctx.html#action)). For each of those, under `execution_requirements`, it says, "information for scheduling the action. See tags for useful keys," and the word "tags" is a a (currently broken) link to https://docs.bazel.build/versions/master/be/common-definitions.html#common-attributes.

Two things:

1. Are an action's `execution_requirements` and a rule's `tags` really the same thing? If not, then they need to be treated separately in the docs.
2. Can you add `nosandbox` to the appropriate place in the docs, wherever that may be?

**Comment by ulfjack** [comment]
All the documented tags are copied to the corresponding actions, and from there to the corresponding spawns. I have a pending change to update the docs.

**Comment by jin** [comment]
`no-sandbox` is now documented through the `tags` link to https://docs.bazel.build/versions/master/be/common-definitions.html#common.tags
