### ISSUE TITLE
Broken documentation links

### ISSUE THREAD

**Issue by mmorearty** [bazelbuild/bazel-website#80]
As I touched on in #79, I've been seeing some broken documentation links on the website recently. Some links take me to a 404 page.

One example: Go to https://docs.bazel.build/versions/master/skylark/lib/ctx.html#action, then scroll down to `execution_requirements`. Where it says "See tags for useful keys," click the "tags" link. It will take you to a 404 page — the URL of the page is:

https://docs.bazel.build/docs/be/common-definitions.html#common.tags

I think the actual desired URL (which I found through a Google search) is:

https://docs.bazel.build/versions/master/be/common-definitions.html#common-attributes

Notice two things about that: (1) the URL is different, and (2) the fragment (the part after `#`) is different.

**Comment by gregestren** [comment]
This is working now.

Let's do follow up bugs for specific instances?
